### ISSUE TITLE
Infografía - Realidad aumentada 

### ISSUE THREAD

**Issue by CxrlosMX** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-CxrlosMX#1]
[Infografía - Realidad aumentada.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-CxrlosMX/files/10842977/Infografia.-.Realidad.aumentada.pdf)

**Comment by Rmz-Rigo** [comment]
CALIFICACION: 19/20
Faltan las referencias.

**Comment by josealfredo79** [comment]
Bien hecho y revisado
